### ISSUE TITLE
Проектирование рефакторинга API backend

### ISSUE THREAD

**Issue by millevi** [YourCodeReview/jobs#29]
Требуется проанализировать код API backend и составить предложения по его рефакторингу.

Цель рефакторинга: облегчение покрытия unit-тестами, увеличение читаемости кода.

Предложения кратко описать в wiki проекта

**Comment by AlenKir** [comment]
Добавлен [Рефакторинг](https://github.com/YourCodeReview/jobs/wiki/%D0%A0%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3). @millevi можешь посмотреть и дать свои комментарии?

**Comment by millevi** [comment]
@AlenKir возражений не имею, все предложения дельные
