### ISSUE TITLE
Задокументировать логику работы страницы списка вакансий

### ISSUE THREAD

**Issue by millevi** [YourCodeReview/jobs#32]
В wiki проекта требуется составить описание работы страницы списка вакансий.

Описание должно быть достаточным для составления по нему тест-кейсов

**Comment by olvsivkov** [comment]
Задача выполнена. Закрываю

https://github.com/YourCodeReview/jobs/wiki/%D0%9B%D0%BE%D0%B3%D0%B8%D0%BA%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9
