### ISSUE TITLE
Задокументировать логику работы формы ввода вакансии

### ISSUE THREAD

**Issue by millevi** [YourCodeReview/jobs#33]
В wiki проекта требуется составить описание работы формы ввода вакансии.

Описание должно быть достаточным для  написания по нему тест-кейсов и постановки задач по доработкам

**Comment by olvsivkov** [comment]
Задача выполнена. Закрываю.

https://github.com/YourCodeReview/jobs/wiki/Логика-работы-формы-ввода-вакансии
